name: COPICOS
favicon: null
layout_spectrum: 0.00421
typography_spectrum: 0.52946
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#383838'
    - '#878787'
    - '#bababa'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
