name: COPICOS
favicon: null
layout_spectrum: 0.00084
typography_spectrum: 0.83755
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfefd'
    - '#8e9ca5'
    - '#d9e1e4'
    - '#040406'
    - '#4c5f6e'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
