name: COPICOS
favicon: null
layout_spectrum: 0.25673
typography_spectrum: 0.83755
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#383838'
    - '#878787'
    - '#bababa'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
