name: COPICOS
favicon: null
layout_spectrum: 0.14711604616604745
typography_spectrum: 0.23733923607505858
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8672260281164199
  lightness: 0.7409986003767699
  saturation: 0.48573047551326454
  rhythmicContrast: 0.7274878169409931
purpose: []
